project_id = "evtvdprofgfryclnvyuo"

[functions.chat]
verify_jwt = false

[functions.send-reminder]
verify_jwt = false

[functions.google-auth]
verify_jwt = false

[functions.google-calendar-sync]
verify_jwt = false
